In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
from keras.models import Sequential
from keras.layers import LSTM, Dropout, Dense, Activation

import datetime

In [2]:
data1 = pd.read_csv('dataset/multiTimeline_w.csv')
data2 = pd.read_excel('dataset/방한_외래관광객21.xlsx')

In [3]:
print(data1)
print(data2)

           date  data
0    2016-01-03    17
1    2016-01-10    18
2    2016-01-17    17
3    2016-01-24    16
4    2016-01-31    15
..          ...   ...
265  2021-01-31    20
266  2021-02-07    22
267  2021-02-14    21
268  2021-02-21    21
269  2021-02-28    20

[270 rows x 2 columns]
            년      인원수
0  2016-01-01  1077431
1  2016-02-01  1126250
2  2016-03-01  1389399
3  2016-04-01  1469674
4  2016-05-01  1492680
..        ...      ...
57 2020-10-01    61585
58 2020-11-01    61764
59 2020-12-01    62344
60 2021-01-01    58397
61 2021-02-01    65582

[62 rows x 2 columns]

In [4]:
# 검색 트래픽을 각 달마다 각각의 테이블로 나누기

# 인덱스를 등록

df1 = data1.set_index('date') #이거 함수 만들까?
print(df1)
df2 = data2.set_index('년')
print(df2)

            data
date
2016-01-03    17
2016-01-10    18
2016-01-17    17
2016-01-24    16
2016-01-31    15
...          ...
2021-01-31    20
2021-02-07    22
2021-02-14    21
2021-02-21    21
2021-02-28    20

[270 rows x 1 columns]
                인원수
년
2016-01-01  1077431
2016-02-01  1126250
2016-03-01  1389399
2016-04-01  1469674
2016-05-01  1492680
...             ...
2020-10-01    61585
2020-11-01    61764
2020-12-01    62344
2021-01-01    58397
2021-02-01    65582

[62 rows x 1 columns]

In [5]:
df1.index = pd.to_datetime(df1.index)
df1

            data
date
2016-01-03    17
2016-01-10    18
2016-01-17    17
2016-01-24    16
2016-01-31    15
...          ...
2021-01-31    20
2021-02-07    22
2021-02-14    21
2021-02-21    21
2021-02-28    20

[270 rows x 1 columns]

In [6]:
df2.index = pd.to_datetime(df2.index)
df2

                인원수
년
2016-01-01  1077431
2016-02-01  1126250
2016-03-01  1389399
2016-04-01  1469674
2016-05-01  1492680
...             ...
2020-10-01    61585
2020-11-01    61764
2020-12-01    62344
2021-01-01    58397
2021-02-01    65582

[62 rows x 1 columns]

In [7]:
df2['2021-02'] # 아 경고는 더이상 안쓴다는 경고인가?

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  """Entry point for launching an IPython kernel.

              인원수
년
2021-02-01  65582

In [8]:
# 간단한 윈도우 생성
# 계획  :각 연도마다 반복문을 돌리고 다음으로 각 달마다 반복문을 돌려서 리스트를 저장하는 것
df_date_y = range(2016,2022)
df_date_m = range(1,13)

results = []

for y in df_date_y:
    for m in df_date_m:
#         str(y) 
#         str(m)
        target_period = str(y) +"-"+str(m)
        print(target_period)
        
# 괜찮긴 하지만 인덱스를 하나씩 읽었으면 한다...

2016-1
2016-2
2016-3
2016-4
2016-5
2016-6
2016-7
2016-8
2016-9
2016-10
2016-11
2016-12
2017-1
2017-2
2017-3
2017-4
2017-5
2017-6
2017-7
2017-8
2017-9
2017-10
2017-11
2017-12
2018-1
2018-2
2018-3
2018-4
2018-5
2018-6
2018-7
2018-8
2018-9
2018-10
2018-11
2018-12
2019-1
2019-2
2019-3
2019-4
2019-5
2019-6
2019-7
2019-8
2019-9
2019-10
2019-11
2019-12
2020-1
2020-2
2020-3
2020-4
2020-5
2020-6
2020-7
2020-8
2020-9
2020-10
2020-11
2020-12
2021-1
2021-2
2021-3
2021-4
2021-5
2021-6
2021-7
2021-8
2021-9
2021-10
2021-11
2021-12

In [9]:
# 일단 재대로 검색이 되는지부터 확인하자.

df1.loc[]

SyntaxError: invalid syntax (<ipython-input-9-d2c1b89736df>, line 3)

In [ ]:
df1.index

In [ ]:
df1.index

In [12]:
df1.index.dt.year

AttributeError: 'DatetimeIndex' object has no attribute 'dt'

In [13]:
test1= df1.index.year
test1

Int64Index([2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016,
            ...
            2020, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021],
           dtype='int64', name='date', length=270)

In [14]:
test1.value

AttributeError: 'Int64Index' object has no attribute 'value'

In [10]:
df_date_y = range(2016,2022)
df_date_m = range(1,13)

def Create_Windows(y, m):
    results = []

    for y in df_date_y:
        for m in df_date_m:
            try:
                target_period = str(y) +"-"+str(m)
                print(target_period)
                results.append(df1[target_period])
            except (KeyError):
                print("종료")
                break
    return results


test2 = Create_Windows(df_date_y,df_date_m)
test2

2016-1
2016-2
2016-3
2016-4
2016-5
2016-6
2016-7
2016-8
2016-9
2016-10
2016-11
2016-12
2017-1
2017-2
2017-3
2017-4
2017-5
2017-6
2017-7
2017-8
2017-9
2017-10
2017-11
2017-12
2018-1
2018-2
2018-3
2018-4
2018-5
2018-6
2018-7
2018-8
2018-9
2018-10
2018-11
2018-12
2019-1
2019-2
2019-3
2019-4
2019-5
2019-6
2019-7
2019-8
2019-9
2019-10
2019-11
2019-12
2020-1
2020-2
2020-3
2020-4
2020-5
2020-6
2020-7
2020-8
2020-9
2020-10
2020-11
2020-12
2021-1
2021-2
2021-3
종료

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  if sys.path[0] == '':

[            data
 date
 2016-01-03    17
 2016-01-10    18
 2016-01-17    17
 2016-01-24    16
 2016-01-31    15,
             data
 date
 2016-02-07    15
 2016-02-14    20
 2016-02-21    17
 2016-02-28    19,
             data
 date
 2016-03-06    20
 2016-03-13    19
 2016-03-20    19
 2016-03-27    24,
             data
 date
 2016-04-03    19
 2016-04-10    19
 2016-04-17    19
 2016-04-24    18,
             data
 date
 2016-05-01    17
 2016-05-08    20
 2016-05-15    20
 2016-05-22    19
 2016-05-29    20,
             data
 date
 2016-06-05    19
 2016-06-12    21
 2016-06-19    17
 2016-06-26    18,
             data
 date
 2016-07-03    20
 2016-07-10    21
 2016-07-17    20
 2016-07-24    18
 2016-07-31    21,
             data
 date
 2016-08-07    19
 2016-08-14    16
 2016-08-21    20
 2016-08-28    20,
             data
 date
 2016-09-04    20
 2016-09-11    20
 2016-09-18    20
 2016-09-25    19,
             data
 date
 2016-10-02    20
 2016-10-09    19
 2016-10-16    19
 2016-10-23    19
 2016-10-30    18,
             data
 date
 2016-11-06    19
 2016-11-13    20
 2016-11-20    19
 2016-11-27    22,
             data
 date
 2016-12-04    41
 2016-12-11    42
 2016-12-18    42
 2016-12-25    46,
             data
 date
 2017-01-01    55
 2017-01-08    53
 2017-01-15    47
 2017-01-22    51
 2017-01-29    48,
             data
 date
 2017-02-05    54
 2017-02-12    50
 2017-02-19    52
 2017-02-26    53,
             data
 date
 2017-03-05    57
 2017-03-12    57
 2017-03-19    57
 2017-03-26    54,
             data
 date
 2017-04-02    48
 2017-04-09    57
 2017-04-16    52
 2017-04-23    47
 2017-04-30    46,
             data
 date
 2017-05-07    42
 2017-05-14    44
 2017-05-21    46
 2017-05-28    44,
             data
 date
 2017-06-04    42
 2017-06-11    44
 2017-06-18    49
 2017-06-25    47,
             data
 date
 2017-07-02    51
 2017-07-09    50
 2017-07-16    45
 2017-07-23    49
 2017-07-30    47,
             data
 date
 2017-08-06    47
 2017-08-13    51
 2017-08-20    50
 2017-08-27    49,
             data
 date
 2017-09-03    50
 2017-09-10    50
 2017-09-17    49
 2017-09-24    47,
             data
 date
 2017-10-01    50
 2017-10-08    51
 2017-10-15    47
 2017-10-22    47
 2017-10-29    51,
             data
 date
 2017-11-05    55
 2017-11-12    48
 2017-11-19    47
 2017-11-26    45,
             data
 date
 2017-12-03    46
 2017-12-10    47
 2017-12-17    47
 2017-12-24    51
 2017-12-31    54,
             data
 date
 2018-01-07    53
 2018-01-14    56
 2018-01-21    55
 2018-01-28    50,
             data
 date
 2018-02-04    59
 2018-02-11    56
 2018-02-18    58
 2018-02-25    57,
             data
 date
 2018-03-04    60
 2018-03-11    56
 2018-03-18    58
 2018-03-25    53,
             data
 date
 2018-04-01    56
 2018-04-08    52
 2018-04-15    49
 2018-04-22    53
 2018-04-29    57,
             data
 date
 2018-05-06    50
 2018-05-13    50
 2018-05-20    55
 2018-05-27    56,
             data
 date
 2018-06-03    57
 2018-06-10    57
 2018-06-17    72
 2018-06-24    71,
             data
 date
 2018-07-01    58
 2018-07-08    58
 2018-07-15    53
 2018-07-22    52
 2018-07-29    57,
             data
 date
 2018-08-05    57
 2018-08-12    60
 2018-08-19    64
 2018-08-26    69,
             data
 date
 2018-09-02    59
 2018-09-09    58
 2018-09-16    53
 2018-09-23    52
 2018-09-30    54,
             data
 date
 2018-10-07    59
 2018-10-14    60
 2018-10-21    55
 2018-10-28    55,
             data
 date
 2018-11-04    51
 2018-11-11    52
 2018-11-18    53
 2018-11-25    51,
             data
 date
 2018-12-02    49
 2018-12-09    49
 2018-12-16    51
 2018-12-23    57
 2018-12-30    61,
             data
 date
 2019-01-06    60
 2019-01-13    58
 2019-01-20    53
 2019-01-27    26,
             data
 date
 2019-02-03    21
 2019-02-10    20
 2019-02-17    24
 2019-02-24    22,
             data
 date
 2019-03-03    21
 2019-03-10    21
 2019-03-17    22
 2019-03-24    23
 2019-03-31    51,
             data
 date
 2019-04-07    55
 2019-04-14    54
 2019-04-21    62
 2019-04-28    59,
             data
 date
 2019-05-05    54
 2019-05-12    52
 2019-05-19    55
 2019-05-26    56,
             data
 date
 2019-06-02    57
 2019-06-09    61
 2019-06-16    61
 2019-06-23    64
 2019-06-30    63,
             data
 date
 2019-07-07    64
 2019-07-14    63
 2019-07-21    61
 2019-07-28    63,
             data
 date
 2019-08-04    64
 2019-08-11    64
 2019-08-18    65
 2019-08-25    61,
             data
 date
 2019-09-01    60
 2019-09-08    57
 2019-09-15    56
 2019-09-22    57
 2019-09-29    53,
             data
 date
 2019-10-06    65
 2019-10-13    55
 2019-10-20    55
 2019-10-27    55,
             data
 date
 2019-11-03    56
 2019-11-10    56
 2019-11-17    59
 2019-11-24    53,
             data
 date
 2019-12-01    51
 2019-12-08    55
 2019-12-15    52
 2019-12-22    56
 2019-12-29    54,
             data
 date
 2020-01-05    60
 2020-01-12    57
 2020-01-19    57
 2020-01-26    56,
             data
 date
 2020-02-02    54
 2020-02-09    54
 2020-02-16    62
 2020-02-23   100,
             data
 date
 2020-03-01    58
 2020-03-08    37
 2020-03-15    32
 2020-03-22    27
 2020-03-29    24,
             data
 date
 2020-04-05    22
 2020-04-12    20
 2020-04-19    22
 2020-04-26    24,
             data
 date
 2020-05-03    24
 2020-05-10    27
 2020-05-17    25
 2020-05-24    27
 2020-05-31    22,
             data
 date
 2020-06-07    23
 2020-06-14    24
 2020-06-21    27
 2020-06-28    25,
             data
 date
 2020-07-05    25
 2020-07-12    23
 2020-07-19    24
 2020-07-26    24,
             data
 date
 2020-08-02    21
 2020-08-09    24
 2020-08-16    20
 2020-08-23    22
 2020-08-30    21,
             data
 date
 2020-09-06    22
 2020-09-13    20
 2020-09-20    23
 2020-09-27    20,
             data
 date
 2020-10-04    22
 2020-10-11    20
 2020-10-18    22
 2020-10-25    20,
             data
 date
 2020-11-01    17
 2020-11-08    19
 2020-11-15    21
 2020-11-22    20
 2020-11-29    19,
             data
 date
 2020-12-06    18
 2020-12-13    21
 2020-12-20    21
 2020-12-27    22,
             data
 date
 2021-01-03    21
 2021-01-10    22
 2021-01-17    20
 2021-01-24    20
 2021-01-31    20,
             data
 date
 2021-02-07    22
 2021-02-14    21
 2021-02-21    21
 2021-02-28    20]

In [ ]:
type(test2)

In [ ]:
test2[2]

In [ ]:
type(test2[2])

In [ ]:
test2

In [ ]:
#df2 정규화

# df2_normalized_data = []
# for i in df2.index:
#     normalized_window =  [((floap))]

# 정규화 안함

In [15]:
# 두 데이터 프레임을 결합

# result = np.array
# 섞는건 x 데이터만 넣고 나중에 y를 집어넣는거지

result = Create_Windows(df_date_y,df_date_m)

2016-1
2016-2
2016-3
2016-4
2016-5
2016-6
2016-7
2016-8
2016-9
2016-10
2016-11
2016-12
2017-1
2017-2
2017-3
2017-4
2017-5
2017-6
2017-7
2017-8
2017-9
2017-10
2017-11
2017-12
2018-1
2018-2
2018-3
2018-4
2018-5
2018-6
2018-7
2018-8
2018-9
2018-10
2018-11
2018-12
2019-1
2019-2
2019-3
2019-4
2019-5
2019-6
2019-7
2019-8
2019-9
2019-10
2019-11
2019-12
2020-1
2020-2
2020-3
2020-4
2020-5
2020-6
2020-7
2020-8
2020-9
2020-10
2020-11
2020-12
2021-1
2021-2
2021-3
종료

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  if sys.path[0] == '':

In [16]:
row = int(round(result.shape[0]*0.9))
train = result[:row, :]
# np.random.shuffle(train)

AttributeError: 'list' object has no attribute 'shape'

In [17]:
import random

random.shuffle(result)

print(result)

[            data
date
2018-06-03    57
2018-06-10    57
2018-06-17    72
2018-06-24    71,             data
date
2020-03-01    58
2020-03-08    37
2020-03-15    32
2020-03-22    27
2020-03-29    24,             data
date
2018-12-02    49
2018-12-09    49
2018-12-16    51
2018-12-23    57
2018-12-30    61,             data
date
2016-06-05    19
2016-06-12    21
2016-06-19    17
2016-06-26    18,             data
date
2016-12-04    41
2016-12-11    42
2016-12-18    42
2016-12-25    46,             data
date
2019-10-06    65
2019-10-13    55
2019-10-20    55
2019-10-27    55,             data
date
2021-02-07    22
2021-02-14    21
2021-02-21    21
2021-02-28    20,             data
date
2019-07-07    64
2019-07-14    63
2019-07-21    61
2019-07-28    63,             data
date
2018-04-01    56
2018-04-08    52
2018-04-15    49
2018-04-22    53
2018-04-29    57,             data
date
2016-01-03    17
2016-01-10    18
2016-01-17    17
2016-01-24    16
2016-01-31    15,             data
date
2019-09-01    60
2019-09-08    57
2019-09-15    56
2019-09-22    57
2019-09-29    53,             data
date
2018-11-04    51
2018-11-11    52
2018-11-18    53
2018-11-25    51,             data
date
2019-11-03    56
2019-11-10    56
2019-11-17    59
2019-11-24    53,             data
date
2020-01-05    60
2020-01-12    57
2020-01-19    57
2020-01-26    56,             data
date
2018-01-07    53
2018-01-14    56
2018-01-21    55
2018-01-28    50,             data
date
2016-09-04    20
2016-09-11    20
2016-09-18    20
2016-09-25    19,             data
date
2018-07-01    58
2018-07-08    58
2018-07-15    53
2018-07-22    52
2018-07-29    57,             data
date
2019-04-07    55
2019-04-14    54
2019-04-21    62
2019-04-28    59,             data
date
2018-05-06    50
2018-05-13    50
2018-05-20    55
2018-05-27    56,             data
date
2018-10-07    59
2018-10-14    60
2018-10-21    55
2018-10-28    55,             data
date
2020-09-06    22
2020-09-13    20
2020-09-20    23
2020-09-27    20,             data
date
2017-10-01    50
2017-10-08    51
2017-10-15    47
2017-10-22    47
2017-10-29    51,             data
date
2019-12-01    51
2019-12-08    55
2019-12-15    52
2019-12-22    56
2019-12-29    54,             data
date
2018-03-04    60
2018-03-11    56
2018-03-18    58
2018-03-25    53,             data
date
2020-10-04    22
2020-10-11    20
2020-10-18    22
2020-10-25    20,             data
date
2016-02-07    15
2016-02-14    20
2016-02-21    17
2016-02-28    19,             data
date
2018-09-02    59
2018-09-09    58
2018-09-16    53
2018-09-23    52
2018-09-30    54,             data
date
2017-11-05    55
2017-11-12    48
2017-11-19    47
2017-11-26    45,             data
date
2018-08-05    57
2018-08-12    60
2018-08-19    64
2018-08-26    69,             data
date
2017-07-02    51
2017-07-09    50
2017-07-16    45
2017-07-23    49
2017-07-30    47,             data
date
2020-06-07    23
2020-06-14    24
2020-06-21    27
2020-06-28    25,             data
date
2020-08-02    21
2020-08-09    24
2020-08-16    20
2020-08-23    22
2020-08-30    21,             data
date
2017-06-04    42
2017-06-11    44
2017-06-18    49
2017-06-25    47,             data
date
2019-03-03    21
2019-03-10    21
2019-03-17    22
2019-03-24    23
2019-03-31    51,             data
date
2018-02-04    59
2018-02-11    56
2018-02-18    58
2018-02-25    57,             data
date
2020-04-05    22
2020-04-12    20
2020-04-19    22
2020-04-26    24,             data
date
2017-02-05    54
2017-02-12    50
2017-02-19    52
2017-02-26    53,             data
date
2016-11-06    19
2016-11-13    20
2016-11-20    19
2016-11-27    22,             data
date
2016-04-03    19
2016-04-10    19
2016-04-17    19
2016-04-24    18,             data
date
2017-12-03    46
2017-12-10    47
2017-12-17    47
2017-12-24    51
2017-12-31    54,             data
date
2017-05-07    42
2017-05-14    44
2017-05-21    46
2017-05-28    44,             data
date
2017-03-05    57
2017-03-12    57
2017-03-19    57
2017-03-26    54,             data
date
2021-01-03    21
2021-01-10    22
2021-01-17    20
2021-01-24    20
2021-01-31    20,             data
date
2019-02-03    21
2019-02-10    20
2019-02-17    24
2019-02-24    22,             data
date
2016-07-03    20
2016-07-10    21
2016-07-17    20
2016-07-24    18
2016-07-31    21,             data
date
2020-02-02    54
2020-02-09    54
2020-02-16    62
2020-02-23   100,             data
date
2019-01-06    60
2019-01-13    58
2019-01-20    53
2019-01-27    26,             data
date
2017-08-06    47
2017-08-13    51
2017-08-20    50
2017-08-27    49,             data
date
2016-03-06    20
2016-03-13    19
2016-03-20    19
2016-03-27    24,             data
date
2017-09-03    50
2017-09-10    50
2017-09-17    49
2017-09-24    47,             data
date
2019-06-02    57
2019-06-09    61
2019-06-16    61
2019-06-23    64
2019-06-30    63,             data
date
2016-08-07    19
2016-08-14    16
2016-08-21    20
2016-08-28    20,             data
date
2017-01-01    55
2017-01-08    53
2017-01-15    47
2017-01-22    51
2017-01-29    48,             data
date
2020-11-01    17
2020-11-08    19
2020-11-15    21
2020-11-22    20
2020-11-29    19,             data
date
2016-05-01    17
2016-05-08    20
2016-05-15    20
2016-05-22    19
2016-05-29    20,             data
date
2020-05-03    24
2020-05-10    27
2020-05-17    25
2020-05-24    27
2020-05-31    22,             data
date
2017-04-02    48
2017-04-09    57
2017-04-16    52
2017-04-23    47
2017-04-30    46,             data
date
2019-08-04    64
2019-08-11    64
2019-08-18    65
2019-08-25    61,             data
date
2020-07-05    25
2020-07-12    23
2020-07-19    24
2020-07-26    24,             data
date
2016-10-02    20
2016-10-09    19
2016-10-16    19
2016-10-23    19
2016-10-30    18,             data
date
2020-12-06    18
2020-12-13    21
2020-12-20    21
2020-12-27    22,             data
date
2019-05-05    54
2019-05-12    52
2019-05-19    55
2019-05-26    56]

In [18]:
result[3]

            data
date
2016-06-05    19
2016-06-12    21
2016-06-19    17
2016-06-26    18

In [19]:
len(result)

62

In [20]:
# x_train과 y_train을 나눈다.
# 좀 특수하게 할꺼니까 기존 방식은 못씀....
train = result

x_train = train[0:10]
x_test = train[10:-1]

print(x_train)
print("")
print(x_test)

[            data
date
2018-06-03    57
2018-06-10    57
2018-06-17    72
2018-06-24    71,             data
date
2020-03-01    58
2020-03-08    37
2020-03-15    32
2020-03-22    27
2020-03-29    24,             data
date
2018-12-02    49
2018-12-09    49
2018-12-16    51
2018-12-23    57
2018-12-30    61,             data
date
2016-06-05    19
2016-06-12    21
2016-06-19    17
2016-06-26    18,             data
date
2016-12-04    41
2016-12-11    42
2016-12-18    42
2016-12-25    46,             data
date
2019-10-06    65
2019-10-13    55
2019-10-20    55
2019-10-27    55,             data
date
2021-02-07    22
2021-02-14    21
2021-02-21    21
2021-02-28    20,             data
date
2019-07-07    64
2019-07-14    63
2019-07-21    61
2019-07-28    63,             data
date
2018-04-01    56
2018-04-08    52
2018-04-15    49
2018-04-22    53
2018-04-29    57,             data
date
2016-01-03    17
2016-01-10    18
2016-01-17    17
2016-01-24    16
2016-01-31    15]

[            data
date
2019-09-01    60
2019-09-08    57
2019-09-15    56
2019-09-22    57
2019-09-29    53,             data
date
2018-11-04    51
2018-11-11    52
2018-11-18    53
2018-11-25    51,             data
date
2019-11-03    56
2019-11-10    56
2019-11-17    59
2019-11-24    53,             data
date
2020-01-05    60
2020-01-12    57
2020-01-19    57
2020-01-26    56,             data
date
2018-01-07    53
2018-01-14    56
2018-01-21    55
2018-01-28    50,             data
date
2016-09-04    20
2016-09-11    20
2016-09-18    20
2016-09-25    19,             data
date
2018-07-01    58
2018-07-08    58
2018-07-15    53
2018-07-22    52
2018-07-29    57,             data
date
2019-04-07    55
2019-04-14    54
2019-04-21    62
2019-04-28    59,             data
date
2018-05-06    50
2018-05-13    50
2018-05-20    55
2018-05-27    56,             data
date
2018-10-07    59
2018-10-14    60
2018-10-21    55
2018-10-28    55,             data
date
2020-09-06    22
2020-09-13    20
2020-09-20    23
2020-09-27    20,             data
date
2017-10-01    50
2017-10-08    51
2017-10-15    47
2017-10-22    47
2017-10-29    51,             data
date
2019-12-01    51
2019-12-08    55
2019-12-15    52
2019-12-22    56
2019-12-29    54,             data
date
2018-03-04    60
2018-03-11    56
2018-03-18    58
2018-03-25    53,             data
date
2020-10-04    22
2020-10-11    20
2020-10-18    22
2020-10-25    20,             data
date
2016-02-07    15
2016-02-14    20
2016-02-21    17
2016-02-28    19,             data
date
2018-09-02    59
2018-09-09    58
2018-09-16    53
2018-09-23    52
2018-09-30    54,             data
date
2017-11-05    55
2017-11-12    48
2017-11-19    47
2017-11-26    45,             data
date
2018-08-05    57
2018-08-12    60
2018-08-19    64
2018-08-26    69,             data
date
2017-07-02    51
2017-07-09    50
2017-07-16    45
2017-07-23    49
2017-07-30    47,             data
date
2020-06-07    23
2020-06-14    24
2020-06-21    27
2020-06-28    25,             data
date
2020-08-02    21
2020-08-09    24
2020-08-16    20
2020-08-23    22
2020-08-30    21,             data
date
2017-06-04    42
2017-06-11    44
2017-06-18    49
2017-06-25    47,             data
date
2019-03-03    21
2019-03-10    21
2019-03-17    22
2019-03-24    23
2019-03-31    51,             data
date
2018-02-04    59
2018-02-11    56
2018-02-18    58
2018-02-25    57,             data
date
2020-04-05    22
2020-04-12    20
2020-04-19    22
2020-04-26    24,             data
date
2017-02-05    54
2017-02-12    50
2017-02-19    52
2017-02-26    53,             data
date
2016-11-06    19
2016-11-13    20
2016-11-20    19
2016-11-27    22,             data
date
2016-04-03    19
2016-04-10    19
2016-04-17    19
2016-04-24    18,             data
date
2017-12-03    46
2017-12-10    47
2017-12-17    47
2017-12-24    51
2017-12-31    54,             data
date
2017-05-07    42
2017-05-14    44
2017-05-21    46
2017-05-28    44,             data
date
2017-03-05    57
2017-03-12    57
2017-03-19    57
2017-03-26    54,             data
date
2021-01-03    21
2021-01-10    22
2021-01-17    20
2021-01-24    20
2021-01-31    20,             data
date
2019-02-03    21
2019-02-10    20
2019-02-17    24
2019-02-24    22,             data
date
2016-07-03    20
2016-07-10    21
2016-07-17    20
2016-07-24    18
2016-07-31    21,             data
date
2020-02-02    54
2020-02-09    54
2020-02-16    62
2020-02-23   100,             data
date
2019-01-06    60
2019-01-13    58
2019-01-20    53
2019-01-27    26,             data
date
2017-08-06    47
2017-08-13    51
2017-08-20    50
2017-08-27    49,             data
date
2016-03-06    20
2016-03-13    19
2016-03-20    19
2016-03-27    24,             data
date
2017-09-03    50
2017-09-10    50
2017-09-17    49
2017-09-24    47,             data
date
2019-06-02    57
2019-06-09    61
2019-06-16    61
2019-06-23    64
2019-06-30    63,             data
date
2016-08-07    19
2016-08-14    16
2016-08-21    20
2016-08-28    20,             data
date
2017-01-01    55
2017-01-08    53
2017-01-15    47
2017-01-22    51
2017-01-29    48,             data
date
2020-11-01    17
2020-11-08    19
2020-11-15    21
2020-11-22    20
2020-11-29    19,             data
date
2016-05-01    17
2016-05-08    20
2016-05-15    20
2016-05-22    19
2016-05-29    20,             data
date
2020-05-03    24
2020-05-10    27
2020-05-17    25
2020-05-24    27
2020-05-31    22,             data
date
2017-04-02    48
2017-04-09    57
2017-04-16    52
2017-04-23    47
2017-04-30    46,             data
date
2019-08-04    64
2019-08-11    64
2019-08-18    65
2019-08-25    61,             data
date
2020-07-05    25
2020-07-12    23
2020-07-19    24
2020-07-26    24,             data
date
2016-10-02    20
2016-10-09    19
2016-10-16    19
2016-10-23    19
2016-10-30    18,             data
date
2020-12-06    18
2020-12-13    21
2020-12-20    21
2020-12-27    22]

In [ ]:
# 자자 그보다. 둘을 서로 연결하고 싶은대 방법이 없나? 이건 나중에....

In [ ]:
# 자 오늘 계획 리스트에 있는 데이터를 하나씩 꺼내서 그 첫번쩨 달을 추출 하고 그 추출한 달과 년을 이용해 입국자를 검색후 리스트에 넣기

In [21]:
x_test

[            data
 date
 2019-09-01    60
 2019-09-08    57
 2019-09-15    56
 2019-09-22    57
 2019-09-29    53,
             data
 date
 2018-11-04    51
 2018-11-11    52
 2018-11-18    53
 2018-11-25    51,
             data
 date
 2019-11-03    56
 2019-11-10    56
 2019-11-17    59
 2019-11-24    53,
             data
 date
 2020-01-05    60
 2020-01-12    57
 2020-01-19    57
 2020-01-26    56,
             data
 date
 2018-01-07    53
 2018-01-14    56
 2018-01-21    55
 2018-01-28    50,
             data
 date
 2016-09-04    20
 2016-09-11    20
 2016-09-18    20
 2016-09-25    19,
             data
 date
 2018-07-01    58
 2018-07-08    58
 2018-07-15    53
 2018-07-22    52
 2018-07-29    57,
             data
 date
 2019-04-07    55
 2019-04-14    54
 2019-04-21    62
 2019-04-28    59,
             data
 date
 2018-05-06    50
 2018-05-13    50
 2018-05-20    55
 2018-05-27    56,
             data
 date
 2018-10-07    59
 2018-10-14    60
 2018-10-21    55
 2018-10-28    55,
             data
 date
 2020-09-06    22
 2020-09-13    20
 2020-09-20    23
 2020-09-27    20,
             data
 date
 2017-10-01    50
 2017-10-08    51
 2017-10-15    47
 2017-10-22    47
 2017-10-29    51,
             data
 date
 2019-12-01    51
 2019-12-08    55
 2019-12-15    52
 2019-12-22    56
 2019-12-29    54,
             data
 date
 2018-03-04    60
 2018-03-11    56
 2018-03-18    58
 2018-03-25    53,
             data
 date
 2020-10-04    22
 2020-10-11    20
 2020-10-18    22
 2020-10-25    20,
             data
 date
 2016-02-07    15
 2016-02-14    20
 2016-02-21    17
 2016-02-28    19,
             data
 date
 2018-09-02    59
 2018-09-09    58
 2018-09-16    53
 2018-09-23    52
 2018-09-30    54,
             data
 date
 2017-11-05    55
 2017-11-12    48
 2017-11-19    47
 2017-11-26    45,
             data
 date
 2018-08-05    57
 2018-08-12    60
 2018-08-19    64
 2018-08-26    69,
             data
 date
 2017-07-02    51
 2017-07-09    50
 2017-07-16    45
 2017-07-23    49
 2017-07-30    47,
             data
 date
 2020-06-07    23
 2020-06-14    24
 2020-06-21    27
 2020-06-28    25,
             data
 date
 2020-08-02    21
 2020-08-09    24
 2020-08-16    20
 2020-08-23    22
 2020-08-30    21,
             data
 date
 2017-06-04    42
 2017-06-11    44
 2017-06-18    49
 2017-06-25    47,
             data
 date
 2019-03-03    21
 2019-03-10    21
 2019-03-17    22
 2019-03-24    23
 2019-03-31    51,
             data
 date
 2018-02-04    59
 2018-02-11    56
 2018-02-18    58
 2018-02-25    57,
             data
 date
 2020-04-05    22
 2020-04-12    20
 2020-04-19    22
 2020-04-26    24,
             data
 date
 2017-02-05    54
 2017-02-12    50
 2017-02-19    52
 2017-02-26    53,
             data
 date
 2016-11-06    19
 2016-11-13    20
 2016-11-20    19
 2016-11-27    22,
             data
 date
 2016-04-03    19
 2016-04-10    19
 2016-04-17    19
 2016-04-24    18,
             data
 date
 2017-12-03    46
 2017-12-10    47
 2017-12-17    47
 2017-12-24    51
 2017-12-31    54,
             data
 date
 2017-05-07    42
 2017-05-14    44
 2017-05-21    46
 2017-05-28    44,
             data
 date
 2017-03-05    57
 2017-03-12    57
 2017-03-19    57
 2017-03-26    54,
             data
 date
 2021-01-03    21
 2021-01-10    22
 2021-01-17    20
 2021-01-24    20
 2021-01-31    20,
             data
 date
 2019-02-03    21
 2019-02-10    20
 2019-02-17    24
 2019-02-24    22,
             data
 date
 2016-07-03    20
 2016-07-10    21
 2016-07-17    20
 2016-07-24    18
 2016-07-31    21,
             data
 date
 2020-02-02    54
 2020-02-09    54
 2020-02-16    62
 2020-02-23   100,
             data
 date
 2019-01-06    60
 2019-01-13    58
 2019-01-20    53
 2019-01-27    26,
             data
 date
 2017-08-06    47
 2017-08-13    51
 2017-08-20    50
 2017-08-27    49,
             data
 date
 2016-03-06    20
 2016-03-13    19
 2016-03-20    19
 2016-03-27    24,
             data
 date
 2017-09-03    50
 2017-09-10    50
 2017-09-17    49
 2017-09-24    47,
             data
 date
 2019-06-02    57
 2019-06-09    61
 2019-06-16    61
 2019-06-23    64
 2019-06-30    63,
             data
 date
 2016-08-07    19
 2016-08-14    16
 2016-08-21    20
 2016-08-28    20,
             data
 date
 2017-01-01    55
 2017-01-08    53
 2017-01-15    47
 2017-01-22    51
 2017-01-29    48,
             data
 date
 2020-11-01    17
 2020-11-08    19
 2020-11-15    21
 2020-11-22    20
 2020-11-29    19,
             data
 date
 2016-05-01    17
 2016-05-08    20
 2016-05-15    20
 2016-05-22    19
 2016-05-29    20,
             data
 date
 2020-05-03    24
 2020-05-10    27
 2020-05-17    25
 2020-05-24    27
 2020-05-31    22,
             data
 date
 2017-04-02    48
 2017-04-09    57
 2017-04-16    52
 2017-04-23    47
 2017-04-30    46,
             data
 date
 2019-08-04    64
 2019-08-11    64
 2019-08-18    65
 2019-08-25    61,
             data
 date
 2020-07-05    25
 2020-07-12    23
 2020-07-19    24
 2020-07-26    24,
             data
 date
 2016-10-02    20
 2016-10-09    19
 2016-10-16    19
 2016-10-23    19
 2016-10-30    18,
             data
 date
 2020-12-06    18
 2020-12-13    21
 2020-12-20    21
 2020-12-27    22]

In [22]:
x_train

[            data
 date
 2018-06-03    57
 2018-06-10    57
 2018-06-17    72
 2018-06-24    71,
             data
 date
 2020-03-01    58
 2020-03-08    37
 2020-03-15    32
 2020-03-22    27
 2020-03-29    24,
             data
 date
 2018-12-02    49
 2018-12-09    49
 2018-12-16    51
 2018-12-23    57
 2018-12-30    61,
             data
 date
 2016-06-05    19
 2016-06-12    21
 2016-06-19    17
 2016-06-26    18,
             data
 date
 2016-12-04    41
 2016-12-11    42
 2016-12-18    42
 2016-12-25    46,
             data
 date
 2019-10-06    65
 2019-10-13    55
 2019-10-20    55
 2019-10-27    55,
             data
 date
 2021-02-07    22
 2021-02-14    21
 2021-02-21    21
 2021-02-28    20,
             data
 date
 2019-07-07    64
 2019-07-14    63
 2019-07-21    61
 2019-07-28    63,
             data
 date
 2018-04-01    56
 2018-04-08    52
 2018-04-15    49
 2018-04-22    53
 2018-04-29    57,
             data
 date
 2016-01-03    17
 2016-01-10    18
 2016-01-17    17
 2016-01-24    16
 2016-01-31    15]

In [23]:
# 에이 서로 반대가 됬내...

a = x_test
x_test = x_train
x_train = a

In [24]:
x_test

[            data
 date
 2018-06-03    57
 2018-06-10    57
 2018-06-17    72
 2018-06-24    71,
             data
 date
 2020-03-01    58
 2020-03-08    37
 2020-03-15    32
 2020-03-22    27
 2020-03-29    24,
             data
 date
 2018-12-02    49
 2018-12-09    49
 2018-12-16    51
 2018-12-23    57
 2018-12-30    61,
             data
 date
 2016-06-05    19
 2016-06-12    21
 2016-06-19    17
 2016-06-26    18,
             data
 date
 2016-12-04    41
 2016-12-11    42
 2016-12-18    42
 2016-12-25    46,
             data
 date
 2019-10-06    65
 2019-10-13    55
 2019-10-20    55
 2019-10-27    55,
             data
 date
 2021-02-07    22
 2021-02-14    21
 2021-02-21    21
 2021-02-28    20,
             data
 date
 2019-07-07    64
 2019-07-14    63
 2019-07-21    61
 2019-07-28    63,
             data
 date
 2018-04-01    56
 2018-04-08    52
 2018-04-15    49
 2018-04-22    53
 2018-04-29    57,
             data
 date
 2016-01-03    17
 2016-01-10    18
 2016-01-17    17
 2016-01-24    16
 2016-01-31    15]

In [25]:
x_train

[            data
 date
 2019-09-01    60
 2019-09-08    57
 2019-09-15    56
 2019-09-22    57
 2019-09-29    53,
             data
 date
 2018-11-04    51
 2018-11-11    52
 2018-11-18    53
 2018-11-25    51,
             data
 date
 2019-11-03    56
 2019-11-10    56
 2019-11-17    59
 2019-11-24    53,
             data
 date
 2020-01-05    60
 2020-01-12    57
 2020-01-19    57
 2020-01-26    56,
             data
 date
 2018-01-07    53
 2018-01-14    56
 2018-01-21    55
 2018-01-28    50,
             data
 date
 2016-09-04    20
 2016-09-11    20
 2016-09-18    20
 2016-09-25    19,
             data
 date
 2018-07-01    58
 2018-07-08    58
 2018-07-15    53
 2018-07-22    52
 2018-07-29    57,
             data
 date
 2019-04-07    55
 2019-04-14    54
 2019-04-21    62
 2019-04-28    59,
             data
 date
 2018-05-06    50
 2018-05-13    50
 2018-05-20    55
 2018-05-27    56,
             data
 date
 2018-10-07    59
 2018-10-14    60
 2018-10-21    55
 2018-10-28    55,
             data
 date
 2020-09-06    22
 2020-09-13    20
 2020-09-20    23
 2020-09-27    20,
             data
 date
 2017-10-01    50
 2017-10-08    51
 2017-10-15    47
 2017-10-22    47
 2017-10-29    51,
             data
 date
 2019-12-01    51
 2019-12-08    55
 2019-12-15    52
 2019-12-22    56
 2019-12-29    54,
             data
 date
 2018-03-04    60
 2018-03-11    56
 2018-03-18    58
 2018-03-25    53,
             data
 date
 2020-10-04    22
 2020-10-11    20
 2020-10-18    22
 2020-10-25    20,
             data
 date
 2016-02-07    15
 2016-02-14    20
 2016-02-21    17
 2016-02-28    19,
             data
 date
 2018-09-02    59
 2018-09-09    58
 2018-09-16    53
 2018-09-23    52
 2018-09-30    54,
             data
 date
 2017-11-05    55
 2017-11-12    48
 2017-11-19    47
 2017-11-26    45,
             data
 date
 2018-08-05    57
 2018-08-12    60
 2018-08-19    64
 2018-08-26    69,
             data
 date
 2017-07-02    51
 2017-07-09    50
 2017-07-16    45
 2017-07-23    49
 2017-07-30    47,
             data
 date
 2020-06-07    23
 2020-06-14    24
 2020-06-21    27
 2020-06-28    25,
             data
 date
 2020-08-02    21
 2020-08-09    24
 2020-08-16    20
 2020-08-23    22
 2020-08-30    21,
             data
 date
 2017-06-04    42
 2017-06-11    44
 2017-06-18    49
 2017-06-25    47,
             data
 date
 2019-03-03    21
 2019-03-10    21
 2019-03-17    22
 2019-03-24    23
 2019-03-31    51,
             data
 date
 2018-02-04    59
 2018-02-11    56
 2018-02-18    58
 2018-02-25    57,
             data
 date
 2020-04-05    22
 2020-04-12    20
 2020-04-19    22
 2020-04-26    24,
             data
 date
 2017-02-05    54
 2017-02-12    50
 2017-02-19    52
 2017-02-26    53,
             data
 date
 2016-11-06    19
 2016-11-13    20
 2016-11-20    19
 2016-11-27    22,
             data
 date
 2016-04-03    19
 2016-04-10    19
 2016-04-17    19
 2016-04-24    18,
             data
 date
 2017-12-03    46
 2017-12-10    47
 2017-12-17    47
 2017-12-24    51
 2017-12-31    54,
             data
 date
 2017-05-07    42
 2017-05-14    44
 2017-05-21    46
 2017-05-28    44,
             data
 date
 2017-03-05    57
 2017-03-12    57
 2017-03-19    57
 2017-03-26    54,
             data
 date
 2021-01-03    21
 2021-01-10    22
 2021-01-17    20
 2021-01-24    20
 2021-01-31    20,
             data
 date
 2019-02-03    21
 2019-02-10    20
 2019-02-17    24
 2019-02-24    22,
             data
 date
 2016-07-03    20
 2016-07-10    21
 2016-07-17    20
 2016-07-24    18
 2016-07-31    21,
             data
 date
 2020-02-02    54
 2020-02-09    54
 2020-02-16    62
 2020-02-23   100,
             data
 date
 2019-01-06    60
 2019-01-13    58
 2019-01-20    53
 2019-01-27    26,
             data
 date
 2017-08-06    47
 2017-08-13    51
 2017-08-20    50
 2017-08-27    49,
             data
 date
 2016-03-06    20
 2016-03-13    19
 2016-03-20    19
 2016-03-27    24,
             data
 date
 2017-09-03    50
 2017-09-10    50
 2017-09-17    49
 2017-09-24    47,
             data
 date
 2019-06-02    57
 2019-06-09    61
 2019-06-16    61
 2019-06-23    64
 2019-06-30    63,
             data
 date
 2016-08-07    19
 2016-08-14    16
 2016-08-21    20
 2016-08-28    20,
             data
 date
 2017-01-01    55
 2017-01-08    53
 2017-01-15    47
 2017-01-22    51
 2017-01-29    48,
             data
 date
 2020-11-01    17
 2020-11-08    19
 2020-11-15    21
 2020-11-22    20
 2020-11-29    19,
             data
 date
 2016-05-01    17
 2016-05-08    20
 2016-05-15    20
 2016-05-22    19
 2016-05-29    20,
             data
 date
 2020-05-03    24
 2020-05-10    27
 2020-05-17    25
 2020-05-24    27
 2020-05-31    22,
             data
 date
 2017-04-02    48
 2017-04-09    57
 2017-04-16    52
 2017-04-23    47
 2017-04-30    46,
             data
 date
 2019-08-04    64
 2019-08-11    64
 2019-08-18    65
 2019-08-25    61,
             data
 date
 2020-07-05    25
 2020-07-12    23
 2020-07-19    24
 2020-07-26    24,
             data
 date
 2016-10-02    20
 2016-10-09    19
 2016-10-16    19
 2016-10-23    19
 2016-10-30    18,
             data
 date
 2020-12-06    18
 2020-12-13    21
 2020-12-20    21
 2020-12-27    22]

In [26]:
# 아...

# 계획대로...
df2

                인원수
년
2016-01-01  1077431
2016-02-01  1126250
2016-03-01  1389399
2016-04-01  1469674
2016-05-01  1492680
...             ...
2020-10-01    61585
2020-11-01    61764
2020-12-01    62344
2021-01-01    58397
2021-02-01    65582

[62 rows x 1 columns]

In [70]:
# def index_Shuffle_tracking()    

arr = np.array([])
for learning_windows in result:
    l_windows_y = learning_windows.index[0].year
    l_windows_m = learning_windows.index[0].month
    print(l_windows_y,l_windows_m)
    arr = np.append(arr,np.array(df2[str(l_windows_y)+"-"+str(l_windows_m)]))

print(arr)

2018 6
2020 3
2018 12
2016 6
2016 12
2019 10
2021 2
2019 7
2018 4
2016 1
2019 9
2018 11
2019 11
2020 1
2018 1
2016 9
2018 7
2019 4
2018 5
2018 10
2020 9
2017 10
2019 12
2018 3
2020 10
2016 2
2018 9
2017 11
2018 8
2017 7
2020 6
2020 8
2017 6
2019 3
2018 2
2020 4
2017 2
2016 11
2016 4
2017 12
2017 5
2017 3
2021 1
2019 2
2016 7
2020 2
2019 1
2017 8
2016 3
2017 9
2019 6
2016 8
2017 1
2020 11
2016 5
2020 5
2017 4
2019 8
2020 7
2016 10
2020 12
2019 5
[1282093.   83497. 1324119. 1554413. 1343398. 1656195.   65582. 1448067.
 1331709. 1077431. 1459664. 1350390. 1456429. 1272708.  956036. 1523928.
 1254833. 1635066. 1238021. 1527832.   65040. 1165638. 1456888. 1366100.
   61585. 1126250. 1278604. 1093217. 1391727. 1008671.   36938.   68797.
  991802. 1535641. 1045415.   29415. 1252080. 1309055. 1469674. 1134068.
  977889. 1233640.   58397. 1201802. 1703495.  685212. 1104803. 1103506.
 1389399. 1078653. 1476218. 1664303. 1220695.   61764. 1492680.   30806.
 1075899. 1586299.   61012. 1587797.   62344. 1485684.]

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.

In [44]:
result[3].index

DatetimeIndex(['2016-06-05', '2016-06-12', '2016-06-19', '2016-06-26'], dtype='datetime64[ns]', name='date', freq=None)

In [46]:
result[3].index[0:1].year

Int64Index([2016], dtype='int64', name='date')

In [47]:
type(result[3].index[0:1].year)

pandas.core.indexes.numeric.Int64Index

In [52]:
if result[3].index[0:1].year == df2.index[0:1].year :
    print('같음')
else:
    print('같지 않음')

같음

In [61]:
df2.index[0:1].year

Int64Index([2016], dtype='int64', name='년')

In [54]:
df2[result[3].index[0:1].year]

KeyError: "None of [Int64Index([2016], dtype='int64', name='date')] are in the [columns]"

In [64]:
# 몇가지 방법이 있다. 입국 자료를 한번씩 계속 스켄하면서 둘러보는 방법과 인덱스 검색을 하는 방법.... 그걸 알아야 한다.
a= 2016
b= 1

df2[str(a)+"-"+str(b)] 일단 작동된다.

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  """

                인원수
년
2016-01-01  1077431

In [69]:
for a in result[2].index.year:
    print(a)

2018
2018
2018
2018
2018

In [66]:
result[2].index.year

Int64Index([2018, 2018, 2018, 2018, 2018], dtype='int64', name='date')

In [81]:

arr = np.array([])
def index_Shuffle_tracking(shuffle_data):
    arr = np.array([])
    for learning_windows in result:
        l_windows_y = learning_windows.index[0].year
        l_windows_m = learning_windows.index[0].month
        print(l_windows_y,l_windows_m)
        arr = np.append(arr,np.array(df2[str(l_windows_y)+"-"+str(l_windows_m)]))
    return arr

In [71]:
arr2 = np.array([])
x_train[1]

            data
date
2018-11-04    51
2018-11-11    52
2018-11-18    53
2018-11-25    51

In [74]:
arr2 = np.append(x_train[1].values)
arr2

TypeError: _append_dispatcher() missing 1 required positional argument: 'values'

In [83]:
y_train = index_Shuffle_tracking(x_train)
y_test = index_Shuffle_tracking(x_test)

2018 6
2020 3
2018 12
2016 6
2016 12
2019 10
2021 2
2019 7
2018 4
2016 1
2019 9
2018 11
2019 11
2020 1
2018 1
2016 9
2018 7
2019 4
2018 5
2018 10
2020 9
2017 10
2019 12
2018 3
2020 10
2016 2
2018 9
2017 11
2018 8
2017 7
2020 6
2020 8
2017 6
2019 3
2018 2
2020 4
2017 2
2016 11
2016 4
2017 12
2017 5
2017 3
2021 1
2019 2
2016 7
2020 2
2019 1
2017 8
2016 3
2017 9
2019 6
2016 8
2017 1
2020 11
2016 5
2020 5
2017 4
2019 8
2020 7
2016 10
2020 12
2019 5
2018 6
2020 3
2018 12
2016 6
2016 12
2019 10
2021 2
2019 7
2018 4
2016 1
2019 9
2018 11
2019 11
2020 1
2018 1
2016 9
2018 7
2019 4
2018 5
2018 10
2020 9
2017 10
2019 12
2018 3
2020 10
2016 2
2018 9
2017 11
2018 8
2017 7
2020 6
2020 8
2017 6
2019 3
2018 2
2020 4
2017 2
2016 11
2016 4
2017 12
2017 5
2017 3
2021 1
2019 2
2016 7
2020 2
2019 1
2017 8
2016 3
2017 9
2019 6
2016 8
2017 1
2020 11
2016 5
2020 5
2017 4
2019 8
2020 7
2016 10
2020 12
2019 5

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.

In [152]:
# 임시 모델

model = Sequential()
model.add(LSTM(4, return_sequences=True, input_shape=(4,1)))
model.add(LSTM(8, return_sequences=False)) #return_sequences 가 뭐지?

model.add(Dense(1, activation='linear'))
model.compile(loss='mse', optimizer='rmsprop')
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_4 (LSTM)                (None, 4, 4)              96
_________________________________________________________________
lstm_5 (LSTM)                (None, 8)                 416
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9
=================================================================
Total params: 521
Trainable params: 521
Non-trainable params: 0
_________________________________________________________________

In [117]:
model.fit(x_train, y_train,
         validation_data=(x_train, y_train),
         batch_size=10,
         epochs=20)

ValueError: Data cardinality is ambiguous:
  x sizes: 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4
  y sizes: 62
Make sure all arrays contain the same number of samples.

In [96]:
#좋았어! 호기심 해결! x크기가 같아야 하는구나!

# 그럼 하나를 결측치로?

#그러면 한 x의 길이가 4또는 5밖에 없으니 for + if 문을 이용해서 작성해 보자...


# x_train[2].append(nan,ignore_index=True)
# 이런 원리로 작동

def add_missing_values(x_ts):
    a = 0
    for row_data in x_ts:
        
        if len(row_data) <= 4 :
            x_train[a].append(None,ignore_index=True)
            print("작동")
        else:
            print("미작동")
        
        a = a+1

In [87]:

len(x_train[2]) # 이걸 응용해서 만들 수 있다.

4

In [88]:
x

51

In [97]:
add_missing_values(x_train)

미작동
작동
작동
작동
작동
작동
미작동
작동
작동
작동
작동
미작동
미작동
작동
작동
작동
미작동
작동
작동
미작동
작동
미작동
작동
미작동
작동
작동
작동
작동
작동
미작동
작동
작동
미작동
작동
미작동
작동
작동
작동
작동
작동
미작동
작동
미작동
미작동
미작동
미작동
미작동
작동
작동
미작동
작동

In [93]:
x_train

[            data
 date
 2019-09-01    60
 2019-09-08    57
 2019-09-15    56
 2019-09-22    57
 2019-09-29    53,
             data
 date
 2018-11-04    51
 2018-11-11    52
 2018-11-18    53
 2018-11-25    51,
             data
 date
 2019-11-03    56
 2019-11-10    56
 2019-11-17    59
 2019-11-24    53,
             data
 date
 2020-01-05    60
 2020-01-12    57
 2020-01-19    57
 2020-01-26    56,
             data
 date
 2018-01-07    53
 2018-01-14    56
 2018-01-21    55
 2018-01-28    50,
             data
 date
 2016-09-04    20
 2016-09-11    20
 2016-09-18    20
 2016-09-25    19,
             data
 date
 2018-07-01    58
 2018-07-08    58
 2018-07-15    53
 2018-07-22    52
 2018-07-29    57,
             data
 date
 2019-04-07    55
 2019-04-14    54
 2019-04-21    62
 2019-04-28    59,
             data
 date
 2018-05-06    50
 2018-05-13    50
 2018-05-20    55
 2018-05-27    56,
             data
 date
 2018-10-07    59
 2018-10-14    60
 2018-10-21    55
 2018-10-28    55,
             data
 date
 2020-09-06    22
 2020-09-13    20
 2020-09-20    23
 2020-09-27    20,
             data
 date
 2017-10-01    50
 2017-10-08    51
 2017-10-15    47
 2017-10-22    47
 2017-10-29    51,
             data
 date
 2019-12-01    51
 2019-12-08    55
 2019-12-15    52
 2019-12-22    56
 2019-12-29    54,
             data
 date
 2018-03-04    60
 2018-03-11    56
 2018-03-18    58
 2018-03-25    53,
             data
 date
 2020-10-04    22
 2020-10-11    20
 2020-10-18    22
 2020-10-25    20,
             data
 date
 2016-02-07    15
 2016-02-14    20
 2016-02-21    17
 2016-02-28    19,
             data
 date
 2018-09-02    59
 2018-09-09    58
 2018-09-16    53
 2018-09-23    52
 2018-09-30    54,
             data
 date
 2017-11-05    55
 2017-11-12    48
 2017-11-19    47
 2017-11-26    45,
             data
 date
 2018-08-05    57
 2018-08-12    60
 2018-08-19    64
 2018-08-26    69,
             data
 date
 2017-07-02    51
 2017-07-09    50
 2017-07-16    45
 2017-07-23    49
 2017-07-30    47,
             data
 date
 2020-06-07    23
 2020-06-14    24
 2020-06-21    27
 2020-06-28    25,
             data
 date
 2020-08-02    21
 2020-08-09    24
 2020-08-16    20
 2020-08-23    22
 2020-08-30    21,
             data
 date
 2017-06-04    42
 2017-06-11    44
 2017-06-18    49
 2017-06-25    47,
             data
 date
 2019-03-03    21
 2019-03-10    21
 2019-03-17    22
 2019-03-24    23
 2019-03-31    51,
             data
 date
 2018-02-04    59
 2018-02-11    56
 2018-02-18    58
 2018-02-25    57,
             data
 date
 2020-04-05    22
 2020-04-12    20
 2020-04-19    22
 2020-04-26    24,
             data
 date
 2017-02-05    54
 2017-02-12    50
 2017-02-19    52
 2017-02-26    53,
             data
 date
 2016-11-06    19
 2016-11-13    20
 2016-11-20    19
 2016-11-27    22,
             data
 date
 2016-04-03    19
 2016-04-10    19
 2016-04-17    19
 2016-04-24    18,
             data
 date
 2017-12-03    46
 2017-12-10    47
 2017-12-17    47
 2017-12-24    51
 2017-12-31    54,
             data
 date
 2017-05-07    42
 2017-05-14    44
 2017-05-21    46
 2017-05-28    44,
             data
 date
 2017-03-05    57
 2017-03-12    57
 2017-03-19    57
 2017-03-26    54,
             data
 date
 2021-01-03    21
 2021-01-10    22
 2021-01-17    20
 2021-01-24    20
 2021-01-31    20,
             data
 date
 2019-02-03    21
 2019-02-10    20
 2019-02-17    24
 2019-02-24    22,
             data
 date
 2016-07-03    20
 2016-07-10    21
 2016-07-17    20
 2016-07-24    18
 2016-07-31    21,
             data
 date
 2020-02-02    54
 2020-02-09    54
 2020-02-16    62
 2020-02-23   100,
             data
 date
 2019-01-06    60
 2019-01-13    58
 2019-01-20    53
 2019-01-27    26,
             data
 date
 2017-08-06    47
 2017-08-13    51
 2017-08-20    50
 2017-08-27    49,
             data
 date
 2016-03-06    20
 2016-03-13    19
 2016-03-20    19
 2016-03-27    24,
             data
 date
 2017-09-03    50
 2017-09-10    50
 2017-09-17    49
 2017-09-24    47,
             data
 date
 2019-06-02    57
 2019-06-09    61
 2019-06-16    61
 2019-06-23    64
 2019-06-30    63,
             data
 date
 2016-08-07    19
 2016-08-14    16
 2016-08-21    20
 2016-08-28    20,
             data
 date
 2017-01-01    55
 2017-01-08    53
 2017-01-15    47
 2017-01-22    51
 2017-01-29    48,
             data
 date
 2020-11-01    17
 2020-11-08    19
 2020-11-15    21
 2020-11-22    20
 2020-11-29    19,
             data
 date
 2016-05-01    17
 2016-05-08    20
 2016-05-15    20
 2016-05-22    19
 2016-05-29    20,
             data
 date
 2020-05-03    24
 2020-05-10    27
 2020-05-17    25
 2020-05-24    27
 2020-05-31    22,
             data
 date
 2017-04-02    48
 2017-04-09    57
 2017-04-16    52
 2017-04-23    47
 2017-04-30    46,
             data
 date
 2019-08-04    64
 2019-08-11    64
 2019-08-18    65
 2019-08-25    61,
             data
 date
 2020-07-05    25
 2020-07-12    23
 2020-07-19    24
 2020-07-26    24,
             data
 date
 2016-10-02    20
 2016-10-09    19
 2016-10-16    19
 2016-10-23    19
 2016-10-30    18,
             data
 date
 2020-12-06    18
 2020-12-13    21
 2020-12-20    21
 2020-12-27    22]

In [110]:
#그럼 하나를 없에보자 
def Delete_a_line(x_ts):
    a = 0
    for row_data in x_ts:
        
        if len(row_data) >= 5 :
#             row_data.drop(labels=[0], axis=0 , inplace=True)
            row_data.drop(row_data.index[0], inplace=True)
            print("작동")
        else:
            print("미작동")
        
        a = a+1
        
    return x_ts

In [111]:
Delete_a_line(x_train)
x_train

작동
미작동
미작동
미작동
미작동
미작동
작동
미작동
미작동
미작동
미작동
작동
작동
미작동
미작동
미작동
작동
미작동
미작동
작동
미작동
작동
미작동
작동
미작동
미작동
미작동
미작동
미작동
작동
미작동
미작동
작동
미작동
작동
미작동
미작동
미작동
미작동
미작동
작동
미작동
작동
작동
작동
작동
작동
미작동
미작동
작동
미작동

C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py:4315: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

[            data
 date
 2019-09-08    57
 2019-09-15    56
 2019-09-22    57
 2019-09-29    53,
             data
 date
 2018-11-04    51
 2018-11-11    52
 2018-11-18    53
 2018-11-25    51,
             data
 date
 2019-11-03    56
 2019-11-10    56
 2019-11-17    59
 2019-11-24    53,
             data
 date
 2020-01-05    60
 2020-01-12    57
 2020-01-19    57
 2020-01-26    56,
             data
 date
 2018-01-07    53
 2018-01-14    56
 2018-01-21    55
 2018-01-28    50,
             data
 date
 2016-09-04    20
 2016-09-11    20
 2016-09-18    20
 2016-09-25    19,
             data
 date
 2018-07-08    58
 2018-07-15    53
 2018-07-22    52
 2018-07-29    57,
             data
 date
 2019-04-07    55
 2019-04-14    54
 2019-04-21    62
 2019-04-28    59,
             data
 date
 2018-05-06    50
 2018-05-13    50
 2018-05-20    55
 2018-05-27    56,
             data
 date
 2018-10-07    59
 2018-10-14    60
 2018-10-21    55
 2018-10-28    55,
             data
 date
 2020-09-06    22
 2020-09-13    20
 2020-09-20    23
 2020-09-27    20,
             data
 date
 2017-10-08    51
 2017-10-15    47
 2017-10-22    47
 2017-10-29    51,
             data
 date
 2019-12-08    55
 2019-12-15    52
 2019-12-22    56
 2019-12-29    54,
             data
 date
 2018-03-04    60
 2018-03-11    56
 2018-03-18    58
 2018-03-25    53,
             data
 date
 2020-10-04    22
 2020-10-11    20
 2020-10-18    22
 2020-10-25    20,
             data
 date
 2016-02-07    15
 2016-02-14    20
 2016-02-21    17
 2016-02-28    19,
             data
 date
 2018-09-09    58
 2018-09-16    53
 2018-09-23    52
 2018-09-30    54,
             data
 date
 2017-11-05    55
 2017-11-12    48
 2017-11-19    47
 2017-11-26    45,
             data
 date
 2018-08-05    57
 2018-08-12    60
 2018-08-19    64
 2018-08-26    69,
             data
 date
 2017-07-09    50
 2017-07-16    45
 2017-07-23    49
 2017-07-30    47,
             data
 date
 2020-06-07    23
 2020-06-14    24
 2020-06-21    27
 2020-06-28    25,
             data
 date
 2020-08-09    24
 2020-08-16    20
 2020-08-23    22
 2020-08-30    21,
             data
 date
 2017-06-04    42
 2017-06-11    44
 2017-06-18    49
 2017-06-25    47,
             data
 date
 2019-03-10    21
 2019-03-17    22
 2019-03-24    23
 2019-03-31    51,
             data
 date
 2018-02-04    59
 2018-02-11    56
 2018-02-18    58
 2018-02-25    57,
             data
 date
 2020-04-05    22
 2020-04-12    20
 2020-04-19    22
 2020-04-26    24,
             data
 date
 2017-02-05    54
 2017-02-12    50
 2017-02-19    52
 2017-02-26    53,
             data
 date
 2016-11-06    19
 2016-11-13    20
 2016-11-20    19
 2016-11-27    22,
             data
 date
 2016-04-03    19
 2016-04-10    19
 2016-04-17    19
 2016-04-24    18,
             data
 date
 2017-12-10    47
 2017-12-17    47
 2017-12-24    51
 2017-12-31    54,
             data
 date
 2017-05-07    42
 2017-05-14    44
 2017-05-21    46
 2017-05-28    44,
             data
 date
 2017-03-05    57
 2017-03-12    57
 2017-03-19    57
 2017-03-26    54,
             data
 date
 2021-01-10    22
 2021-01-17    20
 2021-01-24    20
 2021-01-31    20,
             data
 date
 2019-02-03    21
 2019-02-10    20
 2019-02-17    24
 2019-02-24    22,
             data
 date
 2016-07-10    21
 2016-07-17    20
 2016-07-24    18
 2016-07-31    21,
             data
 date
 2020-02-02    54
 2020-02-09    54
 2020-02-16    62
 2020-02-23   100,
             data
 date
 2019-01-06    60
 2019-01-13    58
 2019-01-20    53
 2019-01-27    26,
             data
 date
 2017-08-06    47
 2017-08-13    51
 2017-08-20    50
 2017-08-27    49,
             data
 date
 2016-03-06    20
 2016-03-13    19
 2016-03-20    19
 2016-03-27    24,
             data
 date
 2017-09-03    50
 2017-09-10    50
 2017-09-17    49
 2017-09-24    47,
             data
 date
 2019-06-09    61
 2019-06-16    61
 2019-06-23    64
 2019-06-30    63,
             data
 date
 2016-08-07    19
 2016-08-14    16
 2016-08-21    20
 2016-08-28    20,
             data
 date
 2017-01-08    53
 2017-01-15    47
 2017-01-22    51
 2017-01-29    48,
             data
 date
 2020-11-08    19
 2020-11-15    21
 2020-11-22    20
 2020-11-29    19,
             data
 date
 2016-05-08    20
 2016-05-15    20
 2016-05-22    19
 2016-05-29    20,
             data
 date
 2020-05-10    27
 2020-05-17    25
 2020-05-24    27
 2020-05-31    22,
             data
 date
 2017-04-09    57
 2017-04-16    52
 2017-04-23    47
 2017-04-30    46,
             data
 date
 2019-08-04    64
 2019-08-11    64
 2019-08-18    65
 2019-08-25    61,
             data
 date
 2020-07-05    25
 2020-07-12    23
 2020-07-19    24
 2020-07-26    24,
             data
 date
 2016-10-09    19
 2016-10-16    19
 2016-10-23    19
 2016-10-30    18,
             data
 date
 2020-12-06    18
 2020-12-13    21
 2020-12-20    21
 2020-12-27    22]

In [113]:
x_train = np.arrat(x_train)
x_train

AttributeError: module 'numpy' has no attribute 'arrat'

In [114]:
x_train = np.arrat([[x_train]])
x_train

AttributeError: module 'numpy' has no attribute 'arrat'

In [ ]:
#판다스 데이터 프레임을 하나 만들어서 봐야하나... 흐아아...

In [122]:
model.fit(x_train, y_train,
         validation_data=(x_train, y_train),
         batch_size=10,
         epochs=20)

ValueError: Data cardinality is ambiguous:
  x sizes: 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4
  y sizes: 62
Make sure all arrays contain the same number of samples.

In [120]:
x_train = np.array(x_train)
x_train # 으아아 진짜!

ValueError: cannot copy sequence with size 4 to array axis with dimension 1

In [119]:
x_train

[            data
 date
 2019-09-08    57
 2019-09-15    56
 2019-09-22    57
 2019-09-29    53,
             data
 date
 2018-11-04    51
 2018-11-11    52
 2018-11-18    53
 2018-11-25    51,
             data
 date
 2019-11-03    56
 2019-11-10    56
 2019-11-17    59
 2019-11-24    53,
             data
 date
 2020-01-05    60
 2020-01-12    57
 2020-01-19    57
 2020-01-26    56,
             data
 date
 2018-01-07    53
 2018-01-14    56
 2018-01-21    55
 2018-01-28    50,
             data
 date
 2016-09-04    20
 2016-09-11    20
 2016-09-18    20
 2016-09-25    19,
             data
 date
 2018-07-08    58
 2018-07-15    53
 2018-07-22    52
 2018-07-29    57,
             data
 date
 2019-04-07    55
 2019-04-14    54
 2019-04-21    62
 2019-04-28    59,
             data
 date
 2018-05-06    50
 2018-05-13    50
 2018-05-20    55
 2018-05-27    56,
             data
 date
 2018-10-07    59
 2018-10-14    60
 2018-10-21    55
 2018-10-28    55,
             data
 date
 2020-09-06    22
 2020-09-13    20
 2020-09-20    23
 2020-09-27    20,
             data
 date
 2017-10-08    51
 2017-10-15    47
 2017-10-22    47
 2017-10-29    51,
             data
 date
 2019-12-08    55
 2019-12-15    52
 2019-12-22    56
 2019-12-29    54,
             data
 date
 2018-03-04    60
 2018-03-11    56
 2018-03-18    58
 2018-03-25    53,
             data
 date
 2020-10-04    22
 2020-10-11    20
 2020-10-18    22
 2020-10-25    20,
             data
 date
 2016-02-07    15
 2016-02-14    20
 2016-02-21    17
 2016-02-28    19,
             data
 date
 2018-09-09    58
 2018-09-16    53
 2018-09-23    52
 2018-09-30    54,
             data
 date
 2017-11-05    55
 2017-11-12    48
 2017-11-19    47
 2017-11-26    45,
             data
 date
 2018-08-05    57
 2018-08-12    60
 2018-08-19    64
 2018-08-26    69,
             data
 date
 2017-07-09    50
 2017-07-16    45
 2017-07-23    49
 2017-07-30    47,
             data
 date
 2020-06-07    23
 2020-06-14    24
 2020-06-21    27
 2020-06-28    25,
             data
 date
 2020-08-09    24
 2020-08-16    20
 2020-08-23    22
 2020-08-30    21,
             data
 date
 2017-06-04    42
 2017-06-11    44
 2017-06-18    49
 2017-06-25    47,
             data
 date
 2019-03-10    21
 2019-03-17    22
 2019-03-24    23
 2019-03-31    51,
             data
 date
 2018-02-04    59
 2018-02-11    56
 2018-02-18    58
 2018-02-25    57,
             data
 date
 2020-04-05    22
 2020-04-12    20
 2020-04-19    22
 2020-04-26    24,
             data
 date
 2017-02-05    54
 2017-02-12    50
 2017-02-19    52
 2017-02-26    53,
             data
 date
 2016-11-06    19
 2016-11-13    20
 2016-11-20    19
 2016-11-27    22,
             data
 date
 2016-04-03    19
 2016-04-10    19
 2016-04-17    19
 2016-04-24    18,
             data
 date
 2017-12-10    47
 2017-12-17    47
 2017-12-24    51
 2017-12-31    54,
             data
 date
 2017-05-07    42
 2017-05-14    44
 2017-05-21    46
 2017-05-28    44,
             data
 date
 2017-03-05    57
 2017-03-12    57
 2017-03-19    57
 2017-03-26    54,
             data
 date
 2021-01-10    22
 2021-01-17    20
 2021-01-24    20
 2021-01-31    20,
             data
 date
 2019-02-03    21
 2019-02-10    20
 2019-02-17    24
 2019-02-24    22,
             data
 date
 2016-07-10    21
 2016-07-17    20
 2016-07-24    18
 2016-07-31    21,
             data
 date
 2020-02-02    54
 2020-02-09    54
 2020-02-16    62
 2020-02-23   100,
             data
 date
 2019-01-06    60
 2019-01-13    58
 2019-01-20    53
 2019-01-27    26,
             data
 date
 2017-08-06    47
 2017-08-13    51
 2017-08-20    50
 2017-08-27    49,
             data
 date
 2016-03-06    20
 2016-03-13    19
 2016-03-20    19
 2016-03-27    24,
             data
 date
 2017-09-03    50
 2017-09-10    50
 2017-09-17    49
 2017-09-24    47,
             data
 date
 2019-06-09    61
 2019-06-16    61
 2019-06-23    64
 2019-06-30    63,
             data
 date
 2016-08-07    19
 2016-08-14    16
 2016-08-21    20
 2016-08-28    20,
             data
 date
 2017-01-08    53
 2017-01-15    47
 2017-01-22    51
 2017-01-29    48,
             data
 date
 2020-11-08    19
 2020-11-15    21
 2020-11-22    20
 2020-11-29    19,
             data
 date
 2016-05-08    20
 2016-05-15    20
 2016-05-22    19
 2016-05-29    20,
             data
 date
 2020-05-10    27
 2020-05-17    25
 2020-05-24    27
 2020-05-31    22,
             data
 date
 2017-04-09    57
 2017-04-16    52
 2017-04-23    47
 2017-04-30    46,
             data
 date
 2019-08-04    64
 2019-08-11    64
 2019-08-18    65
 2019-08-25    61,
             data
 date
 2020-07-05    25
 2020-07-12    23
 2020-07-19    24
 2020-07-26    24,
             data
 date
 2016-10-09    19
 2016-10-16    19
 2016-10-23    19
 2016-10-30    18,
             data
 date
 2020-12-06    18
 2020-12-13    21
 2020-12-20    21
 2020-12-27    22]

In [129]:
np.array(x_train)

ValueError: cannot copy sequence with size 4 to array axis with dimension 1

In [133]:
# 그럼 방법으로 크기를 줄이자...

# 나중에는 len 함수를 써도 되겠지.... 일단은 전부 4로 만들었으니까...

# for i in x_train:
#     i_list = pd.concat([i_list, i])
    
i_list = x_train[0]
for i in range( 1,len(x_train)):
    i_list = pd.concat([i_list,x_train[i]])

In [132]:
len(x_train)

51

In [134]:
i_list

            data
date
2019-09-08    57
2019-09-15    56
2019-09-22    57
2019-09-29    53
2018-11-04    51
...          ...
2016-10-30    18
2020-12-06    18
2020-12-13    21
2020-12-20    21
2020-12-27    22

[204 rows x 1 columns]

In [135]:
x_train_2 = np.array(i_list)

In [136]:
x_train_2

array([[ 57],
       [ 56],
       [ 57],
       [ 53],
       [ 51],
       [ 52],
       [ 53],
       [ 51],
       [ 56],
       [ 56],
       [ 59],
       [ 53],
       [ 60],
       [ 57],
       [ 57],
       [ 56],
       [ 53],
       [ 56],
       [ 55],
       [ 50],
       [ 20],
       [ 20],
       [ 20],
       [ 19],
       [ 58],
       [ 53],
       [ 52],
       [ 57],
       [ 55],
       [ 54],
       [ 62],
       [ 59],
       [ 50],
       [ 50],
       [ 55],
       [ 56],
       [ 59],
       [ 60],
       [ 55],
       [ 55],
       [ 22],
       [ 20],
       [ 23],
       [ 20],
       [ 51],
       [ 47],
       [ 47],
       [ 51],
       [ 55],
       [ 52],
       [ 56],
       [ 54],
       [ 60],
       [ 56],
       [ 58],
       [ 53],
       [ 22],
       [ 20],
       [ 22],
       [ 20],
       [ 15],
       [ 20],
       [ 17],
       [ 19],
       [ 58],
       [ 53],
       [ 52],
       [ 54],
       [ 55],
       [ 48],
       [ 47],
       [ 45],
       [ 57],
       [ 60],
       [ 64],
       [ 69],
       [ 50],
       [ 45],
       [ 49],
       [ 47],
       [ 23],
       [ 24],
       [ 27],
       [ 25],
       [ 24],
       [ 20],
       [ 22],
       [ 21],
       [ 42],
       [ 44],
       [ 49],
       [ 47],
       [ 21],
       [ 22],
       [ 23],
       [ 51],
       [ 59],
       [ 56],
       [ 58],
       [ 57],
       [ 22],
       [ 20],
       [ 22],
       [ 24],
       [ 54],
       [ 50],
       [ 52],
       [ 53],
       [ 19],
       [ 20],
       [ 19],
       [ 22],
       [ 19],
       [ 19],
       [ 19],
       [ 18],
       [ 47],
       [ 47],
       [ 51],
       [ 54],
       [ 42],
       [ 44],
       [ 46],
       [ 44],
       [ 57],
       [ 57],
       [ 57],
       [ 54],
       [ 22],
       [ 20],
       [ 20],
       [ 20],
       [ 21],
       [ 20],
       [ 24],
       [ 22],
       [ 21],
       [ 20],
       [ 18],
       [ 21],
       [ 54],
       [ 54],
       [ 62],
       [100],
       [ 60],
       [ 58],
       [ 53],
       [ 26],
       [ 47],
       [ 51],
       [ 50],
       [ 49],
       [ 20],
       [ 19],
       [ 19],
       [ 24],
       [ 50],
       [ 50],
       [ 49],
       [ 47],
       [ 61],
       [ 61],
       [ 64],
       [ 63],
       [ 19],
       [ 16],
       [ 20],
       [ 20],
       [ 53],
       [ 47],
       [ 51],
       [ 48],
       [ 19],
       [ 21],
       [ 20],
       [ 19],
       [ 20],
       [ 20],
       [ 19],
       [ 20],
       [ 27],
       [ 25],
       [ 27],
       [ 22],
       [ 57],
       [ 52],
       [ 47],
       [ 46],
       [ 64],
       [ 64],
       [ 65],
       [ 61],
       [ 25],
       [ 23],
       [ 24],
       [ 24],
       [ 19],
       [ 19],
       [ 19],
       [ 18],
       [ 18],
       [ 21],
       [ 21],
       [ 22]], dtype=int64)

In [138]:
x_train_2.reshape(-1,1,4)

array([[[ 57,  56,  57,  53]],

       [[ 51,  52,  53,  51]],

       [[ 56,  56,  59,  53]],

       [[ 60,  57,  57,  56]],

       [[ 53,  56,  55,  50]],

       [[ 20,  20,  20,  19]],

       [[ 58,  53,  52,  57]],

       [[ 55,  54,  62,  59]],

       [[ 50,  50,  55,  56]],

       [[ 59,  60,  55,  55]],

       [[ 22,  20,  23,  20]],

       [[ 51,  47,  47,  51]],

       [[ 55,  52,  56,  54]],

       [[ 60,  56,  58,  53]],

       [[ 22,  20,  22,  20]],

       [[ 15,  20,  17,  19]],

       [[ 58,  53,  52,  54]],

       [[ 55,  48,  47,  45]],

       [[ 57,  60,  64,  69]],

       [[ 50,  45,  49,  47]],

       [[ 23,  24,  27,  25]],

       [[ 24,  20,  22,  21]],

       [[ 42,  44,  49,  47]],

       [[ 21,  22,  23,  51]],

       [[ 59,  56,  58,  57]],

       [[ 22,  20,  22,  24]],

       [[ 54,  50,  52,  53]],

       [[ 19,  20,  19,  22]],

       [[ 19,  19,  19,  18]],

       [[ 47,  47,  51,  54]],

       [[ 42,  44,  46,  44]],

       [[ 57,  57,  57,  54]],

       [[ 22,  20,  20,  20]],

       [[ 21,  20,  24,  22]],

       [[ 21,  20,  18,  21]],

       [[ 54,  54,  62, 100]],

       [[ 60,  58,  53,  26]],

       [[ 47,  51,  50,  49]],

       [[ 20,  19,  19,  24]],

       [[ 50,  50,  49,  47]],

       [[ 61,  61,  64,  63]],

       [[ 19,  16,  20,  20]],

       [[ 53,  47,  51,  48]],

       [[ 19,  21,  20,  19]],

       [[ 20,  20,  19,  20]],

       [[ 27,  25,  27,  22]],

       [[ 57,  52,  47,  46]],

       [[ 64,  64,  65,  61]],

       [[ 25,  23,  24,  24]],

       [[ 19,  19,  19,  18]],

       [[ 18,  21,  21,  22]]], dtype=int64)

In [139]:
model.fit(x_train, y_train,
         validation_data=(x_train_2, y_train),
         batch_size=10,
         epochs=20)

ValueError: Data cardinality is ambiguous:
  x sizes: 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4
  y sizes: 62
Make sure all arrays contain the same number of samples.

In [140]:
# y_train_2 = y_train.reshape(-1,1)

In [141]:
x_train_2.reshape(-1,4,1)

array([[[ 57],
        [ 56],
        [ 57],
        [ 53]],

       [[ 51],
        [ 52],
        [ 53],
        [ 51]],

       [[ 56],
        [ 56],
        [ 59],
        [ 53]],

       [[ 60],
        [ 57],
        [ 57],
        [ 56]],

       [[ 53],
        [ 56],
        [ 55],
        [ 50]],

       [[ 20],
        [ 20],
        [ 20],
        [ 19]],

       [[ 58],
        [ 53],
        [ 52],
        [ 57]],

       [[ 55],
        [ 54],
        [ 62],
        [ 59]],

       [[ 50],
        [ 50],
        [ 55],
        [ 56]],

       [[ 59],
        [ 60],
        [ 55],
        [ 55]],

       [[ 22],
        [ 20],
        [ 23],
        [ 20]],

       [[ 51],
        [ 47],
        [ 47],
        [ 51]],

       [[ 55],
        [ 52],
        [ 56],
        [ 54]],

       [[ 60],
        [ 56],
        [ 58],
        [ 53]],

       [[ 22],
        [ 20],
        [ 22],
        [ 20]],

       [[ 15],
        [ 20],
        [ 17],
        [ 19]],

       [[ 58],
        [ 53],
        [ 52],
        [ 54]],

       [[ 55],
        [ 48],
        [ 47],
        [ 45]],

       [[ 57],
        [ 60],
        [ 64],
        [ 69]],

       [[ 50],
        [ 45],
        [ 49],
        [ 47]],

       [[ 23],
        [ 24],
        [ 27],
        [ 25]],

       [[ 24],
        [ 20],
        [ 22],
        [ 21]],

       [[ 42],
        [ 44],
        [ 49],
        [ 47]],

       [[ 21],
        [ 22],
        [ 23],
        [ 51]],

       [[ 59],
        [ 56],
        [ 58],
        [ 57]],

       [[ 22],
        [ 20],
        [ 22],
        [ 24]],

       [[ 54],
        [ 50],
        [ 52],
        [ 53]],

       [[ 19],
        [ 20],
        [ 19],
        [ 22]],

       [[ 19],
        [ 19],
        [ 19],
        [ 18]],

       [[ 47],
        [ 47],
        [ 51],
        [ 54]],

       [[ 42],
        [ 44],
        [ 46],
        [ 44]],

       [[ 57],
        [ 57],
        [ 57],
        [ 54]],

       [[ 22],
        [ 20],
        [ 20],
        [ 20]],

       [[ 21],
        [ 20],
        [ 24],
        [ 22]],

       [[ 21],
        [ 20],
        [ 18],
        [ 21]],

       [[ 54],
        [ 54],
        [ 62],
        [100]],

       [[ 60],
        [ 58],
        [ 53],
        [ 26]],

       [[ 47],
        [ 51],
        [ 50],
        [ 49]],

       [[ 20],
        [ 19],
        [ 19],
        [ 24]],

       [[ 50],
        [ 50],
        [ 49],
        [ 47]],

       [[ 61],
        [ 61],
        [ 64],
        [ 63]],

       [[ 19],
        [ 16],
        [ 20],
        [ 20]],

       [[ 53],
        [ 47],
        [ 51],
        [ 48]],

       [[ 19],
        [ 21],
        [ 20],
        [ 19]],

       [[ 20],
        [ 20],
        [ 19],
        [ 20]],

       [[ 27],
        [ 25],
        [ 27],
        [ 22]],

       [[ 57],
        [ 52],
        [ 47],
        [ 46]],

       [[ 64],
        [ 64],
        [ 65],
        [ 61]],

       [[ 25],
        [ 23],
        [ 24],
        [ 24]],

       [[ 19],
        [ 19],
        [ 19],
        [ 18]],

       [[ 18],
        [ 21],
        [ 21],
        [ 22]]], dtype=int64)

In [145]:
model.fit(x_train, y_train,
         validation_data=(x_train_2, y_train_2),
         batch_size=10,
         epochs=20)

ValueError: Data cardinality is ambiguous:
  x sizes: 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4
  y sizes: 62
Make sure all arrays contain the same number of samples.

In [163]:
y_train_2 = y_train.reshape(-1,1)

In [164]:
y_train_2

array([[1282093.],
       [  83497.],
       [1324119.],
       [1554413.],
       [1343398.],
       [1656195.],
       [  65582.],
       [1448067.],
       [1331709.],
       [1077431.],
       [1459664.],
       [1350390.],
       [1456429.],
       [1272708.],
       [ 956036.],
       [1523928.],
       [1254833.],
       [1635066.],
       [1238021.],
       [1527832.],
       [  65040.],
       [1165638.],
       [1456888.],
       [1366100.],
       [  61585.],
       [1126250.],
       [1278604.],
       [1093217.],
       [1391727.],
       [1008671.],
       [  36938.],
       [  68797.],
       [ 991802.],
       [1535641.],
       [1045415.],
       [  29415.],
       [1252080.],
       [1309055.],
       [1469674.],
       [1134068.],
       [ 977889.],
       [1233640.],
       [  58397.],
       [1201802.],
       [1703495.],
       [ 685212.],
       [1104803.],
       [1103506.],
       [1389399.],
       [1078653.],
       [1476218.],
       [1664303.],
       [1220695.],
       [  61764.],
       [1492680.],
       [  30806.],
       [1075899.],
       [1586299.],
       [  61012.],
       [1587797.],
       [  62344.],
       [1485684.]])

In [146]:
model.fit(x_train, y_train,
         validation_data=(x_train_2, y_train_2),
         batch_size=10,
         epochs=20)

ValueError: Data cardinality is ambiguous:
  x sizes: 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4
  y sizes: 62
Make sure all arrays contain the same number of samples.

In [147]:
y_train_2.reshape(-1,1,1)

array([[[1282093.]],

       [[  83497.]],

       [[1324119.]],

       [[1554413.]],

       [[1343398.]],

       [[1656195.]],

       [[  65582.]],

       [[1448067.]],

       [[1331709.]],

       [[1077431.]],

       [[1459664.]],

       [[1350390.]],

       [[1456429.]],

       [[1272708.]],

       [[ 956036.]],

       [[1523928.]],

       [[1254833.]],

       [[1635066.]],

       [[1238021.]],

       [[1527832.]],

       [[  65040.]],

       [[1165638.]],

       [[1456888.]],

       [[1366100.]],

       [[  61585.]],

       [[1126250.]],

       [[1278604.]],

       [[1093217.]],

       [[1391727.]],

       [[1008671.]],

       [[  36938.]],

       [[  68797.]],

       [[ 991802.]],

       [[1535641.]],

       [[1045415.]],

       [[  29415.]],

       [[1252080.]],

       [[1309055.]],

       [[1469674.]],

       [[1134068.]],

       [[ 977889.]],

       [[1233640.]],

       [[  58397.]],

       [[1201802.]],

       [[1703495.]],

       [[ 685212.]],

       [[1104803.]],

       [[1103506.]],

       [[1389399.]],

       [[1078653.]],

       [[1476218.]],

       [[1664303.]],

       [[1220695.]],

       [[  61764.]],

       [[1492680.]],

       [[  30806.]],

       [[1075899.]],

       [[1586299.]],

       [[  61012.]],

       [[1587797.]],

       [[  62344.]],

       [[1485684.]]])

In [170]:
model.fit(x_train_2, y_train_2[0:51],
         validation_data=(x_train_2, y_train_2[0:51]),
         batch_size=4,
         epochs=20)

Epoch 1/20
13/13 [==============================] - 0s 14ms/step - loss: 1432077860864.0000 - val_loss: 1432077598720.0000
Epoch 2/20
13/13 [==============================] - 0s 10ms/step - loss: 1432077598720.0000 - val_loss: 1432077336576.0000
Epoch 3/20
13/13 [==============================] - 0s 10ms/step - loss: 1432077467648.0000 - val_loss: 1432077205504.0000
Epoch 4/20
13/13 [==============================] - 0s 9ms/step - loss: 1432077205504.0000 - val_loss: 1432076812288.0000
Epoch 5/20
13/13 [==============================] - 0s 9ms/step - loss: 1432076681216.0000 - val_loss: 1432076681216.0000
Epoch 6/20
13/13 [==============================] - 0s 10ms/step - loss: 1432076550144.0000 - val_loss: 1432076156928.0000
Epoch 7/20
13/13 [==============================] - 0s 10ms/step - loss: 1432076025856.0000 - val_loss: 1432075632640.0000
Epoch 8/20
13/13 [==============================] - 0s 9ms/step - loss: 1432075370496.0000 - val_loss: 1432074977280.0000
Epoch 9/20
13/13 [==============================] - 0s 10ms/step - loss: 1432074846208.0000 - val_loss: 1432074584064.0000
Epoch 10/20
13/13 [==============================] - 0s 9ms/step - loss: 1432074190848.0000 - val_loss: 1432073928704.0000
Epoch 11/20
13/13 [==============================] - 0s 10ms/step - loss: 1432073535488.0000 - val_loss: 1432073273344.0000
Epoch 12/20
13/13 [==============================] - 0s 10ms/step - loss: 1432073011200.0000 - val_loss: 1432072617984.0000
Epoch 13/20
13/13 [==============================] - 0s 10ms/step - loss: 1432072617984.0000 - val_loss: 1432072355840.0000
Epoch 14/20
13/13 [==============================] - 0s 9ms/step - loss: 1432072093696.0000 - val_loss: 1432071962624.0000
Epoch 15/20
13/13 [==============================] - 0s 9ms/step - loss: 1432071569408.0000 - val_loss: 1432071307264.0000
Epoch 16/20
13/13 [==============================] - 0s 11ms/step - loss: 1432071307264.0000 - val_loss: 1432071045120.0000
Epoch 17/20
13/13 [==============================] - 0s 9ms/step - loss: 1432070782976.0000 - val_loss: 1432070651904.0000
Epoch 18/20
13/13 [==============================] - 0s 8ms/step - loss: 1432070389760.0000 - val_loss: 1432070258688.0000
Epoch 19/20
13/13 [==============================] - 0s 10ms/step - loss: 1432070127616.0000 - val_loss: 1432069734400.0000
Epoch 20/20
13/13 [==============================] - 0s 9ms/step - loss: 1432069603328.0000 - val_loss: 1432069472256.0000

In [156]:
x_train_2.shape, y_train_2.shape

((204, 1), (62, 1))

In [157]:
x_train_2 = x_train_2.reshape(-1,4,1)
y_train_2 = x_train_2.reshape(-1,1)

In [165]:
x_train_2.shape, y_train_2.shape

((51, 4, 1), (62, 1))

In [167]:
len( y_train_2)

62

In [166]:
y_train_2[0:51]

array([[1282093.],
       [  83497.],
       [1324119.],
       [1554413.],
       [1343398.],
       [1656195.],
       [  65582.],
       [1448067.],
       [1331709.],
       [1077431.],
       [1459664.],
       [1350390.],
       [1456429.],
       [1272708.],
       [ 956036.],
       [1523928.],
       [1254833.],
       [1635066.],
       [1238021.],
       [1527832.],
       [  65040.],
       [1165638.],
       [1456888.],
       [1366100.],
       [  61585.],
       [1126250.],
       [1278604.],
       [1093217.],
       [1391727.],
       [1008671.],
       [  36938.],
       [  68797.],
       [ 991802.],
       [1535641.],
       [1045415.],
       [  29415.],
       [1252080.],
       [1309055.],
       [1469674.],
       [1134068.],
       [ 977889.],
       [1233640.],
       [  58397.],
       [1201802.],
       [1703495.],
       [ 685212.],
       [1104803.],
       [1103506.],
       [1389399.],
       [1078653.],
       [1476218.]])

In [171]:
# 여태까지 있던 일은 그냥 데이터 갯수가 맞지 않아서 생긴 현상...